Step 1 - 

Importing all required libraries 

Loading Data into Notebook

Analyse it further for cleaning

In [ ]:
# Importing all libraries

import pandas as pd
import numpy as np
from sqlalchemy import create_engine

In [ ]:
# Importing os and dataset into notebook

import os

BASE_DIR = os.path.abspath(os.path.join(os.getcwd(), ".."))

sales = pd.read_csv(os.path.join(BASE_DIR, "Sales.csv"))
customer = pd.read_csv(os.path.join(BASE_DIR, "Customer.csv"))
product = pd.read_csv(os.path.join(BASE_DIR, "Product.csv"))
store = pd.read_csv(os.path.join(BASE_DIR, "Store.csv"))
date = pd.read_csv(os.path.join(BASE_DIR, "Date.csv"))
currency = pd.read_csv(os.path.join(BASE_DIR, "Currency.csv"))

/var/folders/qz/809bk0757sz958kkr3n0_v9h0000gn/T/ipykernel_50993/1602061744.py:6: DtypeWarning: Columns (0: zipcode) have mixed types. Specify dtype option on import or set low_memory=False.
  customer = pd.read_csv(os.path.join(BASE_DIR, "Customer.csv"))

In [6]:
sales.head(10)

,orderkey,linenumber,orderdate,deliverydate,customerkey,storekey,productkey,quantity,unitprice,netprice,unitcost,currencycode,exchangerate
0,1000,0,2015-01-01,2015-01-01,947009,400,48,1,112.4625,98.96700,57.3375,GBP,0.64155
1,1000,1,2015-01-01,2015-01-01,947009,400,460,1,749.7500,659.78000,382.2500,GBP,0.64155
2,1001,0,2015-01-01,2015-01-01,1772036,430,1730,2,54.3760,54.37600,25.0040,USD,1.00000
3,1002,0,2015-01-01,2015-01-01,1518349,660,955,4,315.0400,286.68640,144.8800,USD,1.00000
4,1002,1,2015-01-01,2015-01-01,1518349,660,62,7,135.7500,135.75000,62.4300,USD,1.00000
5,1002,2,2015-01-01,2015-01-01,1518349,660,1050,3,499.2000,434.30400,229.5680,USD,1.00000
6,1002,3,2015-01-01,2015-01-01,1518349,660,1608,1,65.9940,58.73466,33.6480,USD,1.00000
7,1003,0,2015-01-01,2015-01-01,1317097,510,85,3,74.9925,74.99250,34.4850,USD,1.00000
8,1004,0,2015-01-01,2015-01-01,254117,80,128,2,114.7200,113.57280,58.4880,CAD,1.15831
9,1004,1,2015-01-01,2015-01-01,254117,80,2079,1,499.4550,499.45500,165.4800,CAD,1.15831

In [7]:
sales.sample(10)

,orderkey,linenumber,orderdate,deliverydate,customerkey,storekey,productkey,quantity,unitprice,netprice,unitcost,currencycode,exchangerate
145151,2873039,0,2022-11-12,2022-11-17,1222395,999999,128,1,143.400,143.4000,73.110,USD,1.00000
41179,1372004,1,2018-10-03,2018-10-06,1508624,999999,785,1,19.000,16.7200,8.740,USD,1.00000
150263,2912062,1,2022-12-21,2022-12-25,1052956,999999,644,3,79.000,69.5200,40.280,GBP,0.82410
77709,1858023,2,2020-02-01,2020-02-09,1319267,999999,478,5,1018.500,875.9100,337.455,USD,1.00000
165320,3047015,1,2023-05-05,2023-05-09,1755167,999999,1361,5,49.990,49.9900,16.560,USD,1.00000
109994,2591003,0,2022-02-03,2022-02-03,1818185,590,1510,2,180.600,155.3160,92.078,USD,1.00000
67324,1719004,0,2019-09-15,2019-09-15,1445290,630,442,2,539.800,491.2180,275.200,USD,1.00000
13115,646001,0,2016-10-07,2016-10-07,1198463,420,1910,3,674.250,613.5675,310.065,GBP,0.81107
31153,1211011,0,2018-04-25,2018-04-25,1941445,570,1607,1,161.991,161.9910,74.493,USD,1.00000
133377,2789030,4,2022-08-20,2022-08-20,664017,130,431,1,369.000,369.0000,188.130,EUR,0.99463

In [13]:
sales.info()

<class 'pandas.DataFrame'>
RangeIndex: 199873 entries, 0 to 199872
Data columns (total 13 columns):
 #   Column        Non-Null Count   Dtype
---  ------        --------------   -----
 0   orderkey      199873 non-null  int64
 1   linenumber    199873 non-null  int64
 2   orderdate     199873 non-null  str
 3   deliverydate  199873 non-null  str
 4   customerkey   199873 non-null  int64
 5   storekey      199873 non-null  int64
 6   productkey    199873 non-null  int64
 7   quantity      199873 non-null  int64
 8   unitprice     199873 non-null  float64
 9   netprice      199873 non-null  float64
 10  unitcost      199873 non-null  float64
 11  currencycode  199873 non-null  str
 12  exchangerate  199873 non-null  float64
dtypes: float64(4), int64(6), str(3)
memory usage: 19.8 MB

Step 2 - 

Standardize Data 

Standardize the values so that it does not give any error in SQL.

In [14]:
def clean_columns(df):
    df.columns = df.columns.str.lower().str.strip().str.replace(" ", "_")
    return df

sales = clean_columns(sales)
customer = clean_columns(customer)
product = clean_columns(product)
store = clean_columns(store)
date = clean_columns(date)
currency = clean_columns(currency)

In [ ]:
# Fixing the Data Type for Sales

sales['orderdate'] = pd.to_datetime(sales['orderdate'])
sales['deliverydate'] = pd.to_datetime(sales['deliverydate'])
sales['quantity'] = sales['quantity'].astype(int)
sales['unitprice'] = sales['unitprice'].astype(float)

In [ ]:
# Fixing the date data type

date['date'] = pd.to_datetime(date['date'])

In [ ]:
# Dropping all duplicate values from all datasets

sales = sales.drop_duplicates()
customer = customer.drop_duplicates()
date = date.drop_duplicates()
currency = currency.drop_duplicates()
product = product.drop_duplicates()
store = store.drop_duplicates()

Step 3 - 

Calculating and Removing all Null Values from our Datasets.

In [ ]:
# 1 For Sales
sales.isnull().sum()

orderkey        0
linenumber      0
orderdate       0
deliverydate    0
customerkey     0
storekey        0
productkey      0
quantity        0
unitprice       0
netprice        0
unitcost        0
currencycode    0
exchangerate    0
dtype: int64

In [ ]:
# 2 For Customers

customer.isnull().sum()

customerkey        0
geoareakey         0
startdt            0
enddt              0
continent          0
gender             0
title              0
givenname          0
middleinitial      0
surname            0
streetaddress      0
city               0
state             66
statefull          0
zipcode            0
country            0
countryfull        0
birthday           0
age                0
occupation         0
company          105
vehicle            0
latitude           0
longitude          0
dtype: int64

As we can see there are null values in company and state so we are filling them with (Unknown).

In [ ]:
customer['company'] = customer['company'].fillna('unknown')
customer['state'] = customer['state'].fillna('unknown')
customer[['company', 'state']].head(20)

                          company state
0              Cut Rite Lawn Care   QLD
1                     Rack N Sack    WA
2                    id Boutiques   NSW
3             Showbiz Pizza Place   TAS
4              Dubrow's Cafeteria   VIC
5                        d.e.m.o.   NSW
6                      Asian Plan   VIC
7          Enrich Garden Services   NSW
8                   Mr. Good Buys   VIC
9                  Franklin Music   NSW
10                       De Pinna   VIC
11                      Multicerv   VIC
12                         Almacs   NSW
13                    Kiddie City    SA
14  Team Designers and Associates    WA
15         Star Merchant Services    SA
16                  Audio Visions   VIC
17                  S&W Cafeteria   VIC
18           Wheels Discount Auto   QLD
19                   Exact Realty   NSW

In [ ]:
# 3 For Currency table

currency.isnull().sum()

date            0
fromcurrency    0
tocurrency      0
exchange        0
dtype: int64

In [ ]:
# 4 For date table

date.isnull().sum()

date                 0
datekey              0
year                 0
yearquarter          0
yearquarternumber    0
quarter              0
yearmonth            0
yearmonthshort       0
yearmonthnumber      0
month                0
monthshort           0
monthnumber          0
dayofweek            0
dayofweekshort       0
dayofweeknumber      0
workingday           0
workingdaynumber     0
dtype: int64

In [ ]:
# 5 Forc Product table

product.isnull().sum()

productkey         0
productcode        0
productname        0
manufacturer       0
brand              0
color              0
weightunit         0
weight             0
cost               0
price              0
categorykey        0
categoryname       0
subcategorykey     0
subcategoryname    0
dtype: int64

In this table there were null values in weight and weight unit columns. so we have filled weight with 0 and weightunit with unknown

In [30]:
product[product['weight'].isnull()].head()
product[product['weightunit'].isnull()].head()

,productkey,productcode,productname,manufacturer,brand,color,weightunit,weight,cost,price,categorykey,categoryname,subcategorykey,subcategoryname
841,842,308100,Contoso Bright Light battery E20 Black,"Contoso, Ltd",Contoso,Black,NaN,NaN,13.71,26.9,3,Computers,308,Computers Accessories
842,843,308101,Contoso Bright Light battery E20 blue,"Contoso, Ltd",Contoso,blue,NaN,NaN,13.71,26.9,3,Computers,308,Computers Accessories
843,844,308102,Contoso Bright Light battery E20 Pink,"Contoso, Ltd",Contoso,Pink,NaN,NaN,13.71,26.9,3,Computers,308,Computers Accessories
844,845,308103,Contoso Bright Light battery E20 White,"Contoso, Ltd",Contoso,White,NaN,NaN,13.71,26.9,3,Computers,308,Computers Accessories
845,846,308104,Contoso Ultraportable Neoprene Sleeve E30 Black,"Contoso, Ltd",Contoso,Black,NaN,NaN,7.95,15.6,3,Computers,308,Computers Accessories

In [31]:
product['weight'] = product['weight'].fillna(0)
product['weightunit'] = product['weightunit'].fillna('Unknown')

In [33]:
store.isnull().sum()

storekey         0
storecode        0
geoareakey       0
countrycode      0
countryname      0
state            0
opendate         0
closedate       58
description      0
squaremeters     1
status          59
dtype: int64

In [ ]:
# 6 For stores table

store['status'].value_counts(dropna=False)

status
Open            59
Closed           8
Restructured     7
Name: count, dtype: int64

In [ ]:
# Therre were nan values in status section so we have filled it with open.

store['status'] = store['status'].fillna('Open')

In [ ]:
# It converts the `closedate` column into a proper datetime format.
# Invalid or unparseable values are automatically turned into `NaT` (missing date)


store['closedate'] = pd.to_datetime(store['closedate'], errors='coerce')

In [38]:
# if status is Open → closedate should be NaT
store.loc[store['status'] == 'Open', 'closedate'] = pd.NaT

In [39]:
store['squaremeters'] = store['squaremeters'].fillna(store['squaremeters'].median())

Step 4 - 

We will calculate the total revenue in sales table.

In [42]:
sales['salesamount'] = sales['quantity'] * sales['unitprice']

In [44]:
sales['salesamount'].head(10)

0     112.4625
1     749.7500
2     108.7520
3    1260.1600
4     950.2500
5    1497.6000
6      65.9940
7     224.9775
8     229.4400
9     499.4550
Name: salesamount, dtype: float64

Step 5 - 

Saving the clean dataset so that we can perform further analysis

In [45]:
from sqlalchemy import create_engine

engine = create_engine("postgresql+psycopg2://postgres:postgres123@localhost:5432/contoso")

In [46]:
sales.to_sql("clean_sales", engine, if_exists="replace", index=False)
customer.to_sql("clean_customer", engine, if_exists="replace", index=False)
product.to_sql("clean_product", engine, if_exists="replace", index=False)
store.to_sql("clean_store", engine, if_exists="replace", index=False)
date.to_sql("clean_date", engine, if_exists="replace", index=False)
currency.to_sql("clean_currency", engine, if_exists="replace", index=False)

325